Project/CarAdvertiser/Controllers/AdvertController.cs
using CarAdvertiser.DTO;
using CarAdvertiser.DTO.ValueEntities;
using CarAdvertiser.Helpers;
using CarAdvertiser.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace CarAdvertiser.Controllers
{
    public class AdvertController : BaseController
    {
        [HttpGet]
        [Authorize]
        public ActionResult AddAdvert()
        {
            AddAdvertViewModel model = new AddAdvertViewModel();
            FillAdvertView();
            FillCheckBoxes(model);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult AddAdvert(AddAdvertViewModel model, HttpPostedFileBase[] files)
        {
            TempData["error"] = null;
            TempData["success"] = null;

            if (!ModelState.IsValid)
            {
                TempData["error"] = "Please fill all mandatory fields!";
                FillAdvertView();
                model.Additionals = new List<CheckBoxList>();
                FillCheckBoxes(model);
                return View(model);
            }

            int saved = 0;

            Advertisement advert = new Advertisement
            {
                AppUserId = User.Identity.GetUserId<int>(),
                CarModelId = model.CarModelId,
                Price = model.Price,
                CurrentMileage = model.CurrentMileage,
                HorsePower = model.HorsePower,
                AmountOfPrevOwners = model.AmountOfPrevOwners,
                AdvertDescription = model.AdvertDescription,
                RegYear = model.RegYear,
                AdvertOpenDate = model.AdvertOpenDate,
                EngineSizeId = model.EngineSizeId,
                BodyTypeId = model.BodyTypeId,
                TransmissionId = model.TransmissionId,
                SeatAmountId = model.SeatAmountId,
                DriveTrainId = model.DriveTrainId,
                FuelTypeId = model.FuelTypeId,
                DoorAmountId = model.DoorAmountId,
                ColourId = model.ColourId,
                AdvertCloseDate = model.AdvertOpenDate.AddDays(model.AdvertAliveDays),
                IsPremium = model.IsPremium,
                IsSold = false,
            };

            List<DateTime> dates = AdvertisementService.GenerateDates(model.AdvertOpenDate,
                model.AdvertOpenDate.AddDays(model.AdvertAliveDays));

            AdvertisementService.Create(advert);
            saved++;

            foreach (DateTime date in dates)
            {
                BookingAvailabilityService.Create(new BookingAvailability
                {
                    AvailableDate = date,
                    AdvertId = advert.Id
                });
                saved++;
            }

            foreach (CheckBoxList addItem in model.Additionals.Where(x => x.IsChecked))
            {
                ExtrasService.Create(new CarExtras
                {
                    EquipmentId = addItem.Id,
                    ExtrasAdvertId = advert.Id
                });
                saved++;
            }

            foreach (HttpPostedFileBase file in files)
            {
                if (file.ContentLength > 0)
                {
                    byte[] data = null;
                    using (MemoryStream target = new MemoryStream())
                    {
                        file.InputStream.CopyTo(target);
                        data = target.ToArray();
                    }

                    ImageService.Create(new Image
                    {
                        ContentType = file.ContentType,
                        ImageName = file.FileName,
                        ImageData = data
                    });
                    saved++;
                }
            }

            if (Uow.Commit() == saved)
            {
                List<WantedCar> wantedList = WantedCarService.GetAllByPriceMileage(model.Price, model.RegYear);

                if (wantedList.Any())
                {
                    List<string> emails = new List<string>();
                    foreach (int userId in wantedList.Select(x => x.UserId))
                    {
                        emails.Add(RepositoryAppUserV2.FindById(userId).Email);
                    }
                    Email.InterestedAdvertAdded(emails.ToArray(), advert);
                }

                TempData["success"] = $"Thank you! Confirmation email has been sent to your inbox";

                Email.Send(new[] { User.Identity.GetEmail() }, $"Greetings from Car Advertiser. Your advert will be live from {model.AdvertOpenDate} and will close on {model.AdvertOpenDate.AddDays(model.AdvertAliveDays)}");

                return RedirectToAction("AddAdvert");
            }

            TempData["error"] = $"Error Occured When Trying To Add The Advert. Please try again!";
            return View(model);
        }

        private void FillAdvertView()
        {
            ViewData["Make"] = ManufacturerService.GetAllNotDeleted().Select(x => new SelectListItem
            {
                Text = x.Value,
                Value = x.Id.ToString()
            });

            ViewData["Model"] = ModelService.GetAllNotDeleted(x => x.CarManufacturer).Select(x => new SelectListItem
            {
                Text = x.Value,
                Value = x.Id.ToString()
            });

            ViewData["Engine"] = EngineSizeService.GetAllNotDeleted().Select(x => new SelectListItem
            {
                Text = x.Size.ToString(),
                Value = x.Id.ToString()
            }).OrderBy(x => x.Text);

            ViewData["BodyType"] = BodyTypeService.GetAllNotDeleted().Select(x => new SelectListItem
            {
                Text = x.Value,
                Value = x.Id.ToString()
            }).OrderBy(x => x.Text);

            ViewData["Transmission"] = TransmissionService.GetAllNotDeleted().Select(x => new SelectListItem
            {
                Text = x.Value,
                Value = x.Id.ToString()
            }).OrderBy(x => x.Text);

            ViewData["Seat"] = SeatAmountService.GetAllNotDeleted().Select(x => new SelectListItem
            {
                Text = x.NumberOfSeats.ToString(),
                Value = x.Id.ToString()
            });

            ViewData["DriveTrain"] = DriveTrainService.GetAllNotDeleted().Select(x => new SelectListItem
            {
                Text = x.Value,
                Value = x.Id.ToString()
            }).OrderBy(x => x.Text);

            ViewData["FuelType"] = FuelTypeService.GetAllNotDeleted().Select(x => new SelectListItem
            {
                Text = x.Value,
                Value = x.Id.ToString()
            }).OrderBy(x => x.Text);

            ViewData["Door"] = DoorService.GetAllNotDeleted().Select(x => new SelectListItem
            {
                Text = x.NumberOfDoors.ToString(),
                Value = x.Id.ToString()
            }).OrderBy(x => x.Text);

            ViewData["Colour"] = ColourService.GetAllNotDeleted().Select(x => new SelectListItem
            {
                Text = x.Value,
                Value = x.Id.ToString()
            }).OrderBy(x => x.Text);

            List<SelectListItem> years = new List<SelectListItem>();
            {
                for (int i = 1960; i <= DateTime.Now.Year; i++)
                {
                    years.Add(new SelectListItem
                    {
                        Value = i.ToString(),
                        Text = i.ToString()
                    });
                }
            }
            ViewData["Year"] = years.ToList().OrderByDescending(x => x.Text);

            List<SelectListItem> days = new List<SelectListItem>();
            {
                for (int i = 1; i < 31; i++)
                {
                    days.Add(new SelectListItem
                    {
                        Value = i.ToString(),
                        Text = i.ToString()
                    });
                }
            }
            ViewData["Days"] = days.ToList();
        }

        private void FillCheckBoxes(AddAdvertViewModel model)
        {
            foreach (AdditionalEquipment item in EquipmentService.GetAllNotDeleted())
            {
                CheckBoxList newItem = new CheckBoxList
                {
                    Id = item.Id,
                    Display = item.Value,
                    IsChecked = false
                };

                if (model.Additionals.All(x => x.Id != newItem.Id))
                    model.Additionals.Add(newItem);
            }
        }

        [HttpGet]
        [Authorize]
        public ActionResult AddWantedCar()
        {
            WantedCarViewModel wanted = new WantedCarViewModel();
            FillWantedCarView();
            return View(wanted);
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddWantedCar(WantedCarViewModel wanted)
        {
            TempData["error"] = null;
            TempData["success"] = null;

            if (!ModelState.IsValid)
            {
                FillWantedCarView();
                return View(wanted);
            }

            int saved = 0;
            WantedCar wantedCar = new WantedCar
            {
                MinimumYear = wanted.MinYear,
                MaxPrice = wanted.MaxPrice,
                IsWanted = true,
                UserId = User.Identity.GetUserId<int>(),
                ModelId = wanted.Model
            };
            WantedCarService.Create(wantedCar);
            saved++;
            if (Uow.Commit() == saved)
            {
                List<Advertisement> existInDb = AdvertisementService.GetAllByWanted(wanted.Make, wanted.Model, wanted.MinYear, wanted.MaxPrice);

                if (existInDb.Any())
                {

Project/CarAdvertiser/Controllers/MessageController.cs
using System;
using System.Net;
using CarAdvertiser.Helpers;
using System.Web.Mvc;
using CarAdvertiser.DTO;
using Microsoft.AspNet.Identity;

namespace CarAdvertiser.Controllers
{
    [Authorize]
    public class MessageController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }


        public JsonResult GetAllUnreadMessages()
        {
            return Json(MessageHelpers.GetAllUnreadMessages(User.Identity.GetUserId<int>()), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllUndeletedMessages()
        {
            return Json(MessageHelpers.GetAllUndeletedMessages(User.Identity.GetUserId<int>()), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DeleteMessage(int messageId)
        {
            MessagesService.SetRead(messageId);
            MessagesService.Delete(messageId);
            Uow.Commit();
            return Json(new { result = "OK" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Authorize]
        public ActionResult SendMessage(string message, int toId)
        {
            if (string.IsNullOrEmpty(message))
            {
                return new JsonErrorResult(HttpStatusCode.InternalServerError)
                {
                    Data = "Missing message!",
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }

            try
            {
                MessagesService.Create(new Messages
                {
                    MessageContent = message,
                    ReceiverId = toId,
                    SenderId = User.Identity.GetUserId<int>()
                });
                Uow.Commit();
            }
            catch (Exception ex)
            {
                return new JsonErrorResult(HttpStatusCode.InternalServerError)
                {
                    Data = ex.Message,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }

            return Json(new { result = "Message sent successfully" }, JsonRequestBehavior.AllowGet);
        }
    }
}

Project/CarAdvertiser/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using CarAdvertiser.BLL.Services;
using CarAdvertiser.DTO;
using CarAdvertiser.Helpers;
using CarAdvertiser.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;

namespace CarAdvertiser.Controllers
{
    public class UserController : BaseController
    {
        // GET: User
        [Authorize]
        [HttpGet]
        public ActionResult UserPanel()
        {
            ViewBag.UserAdvertCount = AdvertisementService
                .GetAllActiveAdverts().Count(x => x.AppUserId == User.Identity.GetUserId<int>());

            ViewBag.UserExpiredAdvertCount = AdvertisementService
                .GetAllExpiredAdverts().Count(x => x.AppUserId == User.Identity.GetUserId<int>());

            ViewBag.UserSoldCars = AdvertisementService
                .GetAll().Where(x => x.AppUserId == User.Identity.GetUserId<int>()).Count(x => x.IsSold == true);

            ViewBag.MyBookingsCount = BookingService.GetAll().Count(x => x.BookingUserId == User.Identity.GetUserId<int>());

            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult ManageAdverts()
        {
            IEnumerable<Advertisement> userAdverts = AdvertisementService.GetAllActiveAdverts().Where(x => x.AppUserId == User.Identity.GetUserId<int>());

            List<UserAdvertsViewModel> result = new List<UserAdvertsViewModel>();
            foreach (Advertisement item in userAdverts)
            {
                result.Add(new UserAdvertsViewModel
                {
                    AdvertId = item.Id,
                    Make = item.CarModel.CarManufacturer.Value,
                    Model = item.CarModel.Value,
                    Price = item.Price,
                    ClosingDate = item.AdvertCloseDate,
                    IsSold = item.IsSold
                });
            }
            return View("ManageAdverts", result);
        }

        //[HttpPost]
        [Authorize]
        [NoDirectAccess]
        [HttpGet]
        public ActionResult ExpiredAdverts()
        {
            IEnumerable<Advertisement> expiredAdverts = AdvertisementService.GetAllExpiredAdverts()
                .Where(x => x.AppUserId == User.Identity.GetUserId<int>());

            List<UserAdvertsViewModel> result = new List<UserAdvertsViewModel>();
            foreach (Advertisement item in expiredAdverts)
            {
                result.Add(new UserAdvertsViewModel
                {
                    AdvertId = item.Id,
                    Make = item.CarModel.CarManufacturer.Value,
                    Model = item.CarModel.Value,
                    Price = item.Price,
                    ClosingDate = item.AdvertCloseDate,
                    IsSold = item.IsSold
                });
            }

            return View(result);
        }

        [Authorize]
        [NoDirectAccess]
        [HttpGet]
        public ActionResult SoldCars()
        {
            IEnumerable<Advertisement> soldCars = AdvertisementService.GetAll()
                .Where(x => x.AppUserId == User.Identity.GetUserId<int>() & x.IsSold);

            List<UserAdvertsViewModel> result = new List<UserAdvertsViewModel>();
            foreach (Advertisement item in soldCars)
            {
                result.Add(new UserAdvertsViewModel
                {
                    AdvertId = item.Id,
                    Price = item.Price,
                    ClosingDate = item.AdvertCloseDate
                });
            }

            return View(result);
        }

        [HttpPost]
        public ActionResult SetAsSold(int id)
        {
            if (ModelState.IsValid)
            {
                Advertisement adv = AdvertisementService.FindById(id);
                adv.IsSold = true;
                AdvertisementService.Update(adv);
                Uow.Commit();

            }
            return View("UserPanel");
        }

        [Authorize]
        [NoDirectAccess]
        [HttpGet]
        public ActionResult MyBookings()
        {
            IEnumerable<Booking> myBookings = BookingService.GetAll()
                .Where(x => x.BookingUserId == User.Identity.GetUserId<int>());

            List<MyBookingsViewModel> result = new List<MyBookingsViewModel>();
            foreach (Booking item in myBookings)
            {
                result.Add(new MyBookingsViewModel
                {
                    BookingId = item.Id,
                    AvailabilityId = item.AvailabilityId,
                    BookingUserId = item.BookingUserId,
                });
            }

            return View(result);
        }

        [Authorize]
        [HttpGet]
        public ActionResult EditExpiredAdvert()
        {

            return View();
        }

        [Authorize]
        public ActionResult AdminPanel()
        {
            return View();
        }
    }
}

Project/CarAdvertiser/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Car Advertiser</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper")
    @Scripts.Render("~/bundles/bootstrap")
    <link href="@Url.Content("~/Content/Personal.css")" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script src="~/Scripts/jquery.signalR-2.4.1.min.js"></script>

    <!--reference the autogenerated SignalR hub script-->
    <script src="~/signalr/hubs"></script>

    <script type="text/javascript">
        var replyToId;

        $(function () {

            var hub = $.connection.carAdvertiserHub;

            //declaring a function on the hub so the server can invoke it
            hub.client.displayMessage = function() {
                getData();
            };

            //Start the connection
            $.connection.hub.start();
            getData();
        });

        function getData() {
            $.ajax({
                url: '@Url.Action("GetAllUnreadMessages", "Message")',
                type: 'GET',
                datatype: 'json',
                success: function(result) {

                    var data = $.parseJSON(result);
                    if (data.length > 0) {
                        $("#msgCnt").text(data.length);
                        $("#msgCnt2").text(data.length);
                    }
                },
                error: function(result) {
                    console.log("ERROR");
                    console.log(result);
                }
            });

            var divNotification = $("#divNotification");

            $.ajax({
                url: '@Url.Action("GetAllUndeletedMessages", "Message")',
                type: 'GET',
                datatype: 'json',
                success: function(result) {

                    var data = $.parseJSON(result);

                    if (data.length > 0) {
                        divNotification.empty();

                        for (var i = 0; i < data.length; i++) {
                            var id = data[i].MessageId;
                            var message =
                                '<div class="alert alert-success alert-dismissable openDiv" id="open' + id + '"><a id="' + id + '" href="#" class="close close-click" data-dismiss="alert" aria-label="close">&times;</a>SENDER: ' + data[i].SenderName + ' | RECEIVED ON: ' + data[i].ReceivedDate + '</div>' +
                                    '<div class="alert alert-success alert-dismissable closeDiv hide" id="clos' + id + '"><a id="' + id + '" href="#" class="close close-click" data-dismiss="alert" aria-label="close">&times;</a>SENDER: ' + data[i].SenderName + ' | RECEIVED ON: ' + data[i].ReceivedDate + '</div>' +
                                    '<div class="messageDiv hide" id="mesg' + id + '">MESSAGE: ' + data[i].Message + '<i id="' + id + '" class="fas fa-reply float-right message-reply-icon" data-toggle="modal" data-target="#replyModal" data-id="' + data[i].SenderId + '"></i></div>';

                            divNotification.append(message);
                        }

                        $('.message-reply-icon').on('click', function () {
                            replyToId = $(this).data('id');
                        });

                        $(".close-click").click(function(event) {
                            var messageId = $(this).attr("id");
                            var id = event.target.id;
                            deleteMessage(messageId);
                        });

                        $(".openDiv").click(function (event) {
                            var id = event.target.id;
                            var component = id.substring(0, 4);
                            var componentId = id.substr(4);
                            if ($('#mesg'+componentId+':visible').length === 0) {
                                $('#mesg' + componentId).fadeIn('slow');
                                $('#open' + componentId).hide();
                                $('#clos' + componentId).show();
                            }
                        });

                        $(".closeDiv").click(function (event) {
                            var id = event.target.id;
                            var component = id.substring(0, 4);
                            var componentId = id.substr(4);

                            if ($('#mesg' + componentId +':visible').length !== 0) {
                                $('#mesg' + componentId).hide();
                                $('#open' + componentId).show();
                                $('#clos' + componentId).hide();
                            }
                        });


                    }
                },
                error: function(result) {
                    console.log("ERROR");
                    console.log(result);
                }
            });
        }

        function deleteMessage(messageId) {
            $.ajax({
                url: '@Url.Action("DeleteMessage", "Message")',
                type: 'POST',
                datatype: 'json',
                data: { messageId: messageId },
                success: function(result) {
                    console.log("Message " + messageId + " deleted");
                },
                error: function(result) {
                    console.log("ERROR");
                    console.log(result);
                }
            });
        }

    </script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
        @Html.ActionLink("Car Advertiser", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="#navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto text-uppercase">
                <li class="nav-link">@Html.ActionLink("Advanced Search", "AdvertSearch", "Advert")</li>
                <li class="nav-link">@Html.ActionLink("Wanted Car", "AddWantedCar", "Advert")</li>
                @if (User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
                {
                    <li class="nav-link">@Html.ActionLink("User Panel", "UserPanel", "User")</li>
                }
                @if (User.IsInRole("Admin"))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Admin
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @if (User.IsInRole("Admin"))
                            {
                                <a class="dropdown-item" href="">Role management</a>
                                <a class="dropdown-item" href="@Url.Action("AdminPanel", "Admin")">Admin Panel</a>
                                <hr />
                                <a class="dropdown-item" href="@Url.Action("InitializeDatabase", "Database")">Initialize Database</a>
                                <a class="dropdown-item" href="@Url.Action("Purge", "Database")">Purge Database</a>
                            }
                        </div>
                    </li>
                }
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-link">
                        @Html.ActionLink("My messages", "Index", "Message")
                        <i class="fa fa-envelope fa-1x fa-border badge" id="msgCnt2"></i>
                    </li>
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    <div class="container-fluid body-content">
        @RenderBody()
    </div>

    <div class="push"></div>

    <footer>
        <p>&copy; @DateTime.Now.Year - Car Advertiser | All rights reserved | Created by Marcin Sorokosz </p>
    </footer>

    @RenderSection("scripts", required: false)
</body>
</html>